Add Filling form POM, Types and BDD test
Sanberqui18/cypress-training pull request #13
Opened 2024-01-03 18:43 UTC by Sanberqui18

Tests Passed:
![Screen Shot 2024-01-03 at 1 43 18 PM](https://github.com/Sanberqui18/cypress-training/assets/119998036/d78b7da5-e99c-481e-9d2a-8b2933ffc873)

2024-01-03 20:46 UTC, salorrego requested changes

2024-01-03 20:46 UTC, salorrego commented on cypress/e2e/filling.form.cy.ts
> +    describe("When the user fills out all the form and click on the submit button", () => {
```suggestion
    describe("When the user fills out all the form and clicks on the submit button", () => {
```

2024-01-03 20:46 UTC, salorrego commented on cypress/e2e/filling.form.cy.ts
> +      it("Then the user is rediected to the confirmation page and the data is correct", () => {
```suggestion
      it("Then the user should be redirected to the confirmation page and the displayed data should be correct", () => {
```

2024-01-03 20:46 UTC, salorrego commented on cypress/e2e/filling.form.cy.ts
> +        confirmationForm.closePopUp();
why this action?

2024-01-03 20:46 UTC, salorrego commented on cypress/pages/confirmation.form.ts
> +  getTitle(): Cypress.Chainable<JQuery<HTMLElement>> {
awesome typing

2024-01-03 20:46 UTC, salorrego commented on cypress/pages/confirmation.form.ts
> +  closePopUp() {
```suggestion
  closePopUp(): void {
```

2024-01-03 20:46 UTC, salorrego commented on cypress/pages/form.ts
> +        //@ts-ignore
??

2024-01-03 20:46 UTC, salorrego commented on cypress/support/commands.ts
> +});
why?
this probably means you have a problem with the tests

2024-01-03 21:07 UTC, Sanberqui18 commented on cypress/e2e/filling.form.cy.ts
> +    describe("When the user fills out all the form and click on the submit button", () => {
done

2024-01-04 15:14 UTC, salorrego approved these changes
awesome

2024-01-04 16:05 UTC, merged